/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonLink: typeof import('./components/Nav/ButtonLink.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    HeaderSection: typeof import('./components/Layout/HeaderSection.vue')['default']
    NavLink: typeof import('./components/Nav/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchLink: typeof import('./components/Layout/SearchLink.vue')['default']
    ToolbarTitle: typeof import('./components/Layout/ToolbarTitle.vue')['default']
  }
}
